// Original learning activities mapped to the OCR specification, version 7 (June 2026).
// These are teaching simulations, not OCR set assignments or evidence of hands-on competence.
export const AAQ_SPEC_URL = 'https://www.ocr.org.uk/Images/697578-specification-cambridge-advanced-national-in-human-biology.pdf';

export const AAQ_PRACTICALS = [
  {
    id: 'aaq-microscopy', scene: 'microscopy', group: 'biomedical', linkedUnits: ['F170'], title: 'Calibrated microscopy', subtitle: 'Measure human cells',
    unit: 'F173', topic: '2.1 · Microscopy', page: 71, color: '#4b8fe2', icon: '🔬',
    objective: 'Calibrate the eyepiece scale and measure a model epithelial cell in micrometres.',
    principle: 'Magnification enlarges an image. Calibration converts eyepiece divisions into a real specimen size; it must be repeated when the objective changes.',
    steps: [
      { title: 'Prepare the slide', detail: 'Place the prepared epithelial slide on the stage and begin with the low-power objective.', action: 'prepare' },
      { title: 'Calibrate the scale', detail: 'Align the graticule with the stage micrometer. Establish micrometres per eyepiece division.', action: 'calibrate' },
      { title: 'Focus and measure', detail: 'Select the objective, focus the cell boundary and read the calibrated scale across the cell.', action: 'run' },
      { title: 'Record and evaluate', detail: 'Record the size and unit. Explain why a larger image does not mean a larger cell.', action: 'record' },
    ],
    equipment: ['Light microscope', 'Prepared epithelial slide', 'Stage micrometer', 'Eyepiece graticule'],
    parameter: { label: 'Objective magnification', unit: '×', min: 10, max: 40, step: 10, value: 20 },
    variable: 'Change objective magnification; observe image size and calibrated cell size.',
    controls: 'Use the same cell and the same eyepiece. Recalibrate for each objective.',
    caution: 'Handle glass slides carefully and keep the objective clear of the coverslip.',
    simLimit: 'The rendered cell is an illustrative model; a real specimen has irregular boundaries and focusing uncertainty.',
    question: { prompt: 'An objective is changed from 10× to 40×. What should happen to the calculated size of the same cell?', options: ['It stays approximately the same after recalibration.', 'It becomes four times larger.', 'It becomes four times smaller.'], answer: 0, explanation: 'The image grows, but the physical cell does not. The new calibration compensates for the changed magnification.' },
  },
  {
    id: 'aaq-dna', scene: 'dna', group: 'genetics', linkedUnits: ['F173'], title: 'DNA sample preparation', subtitle: 'From cells to genetic testing',
    unit: 'F172', topic: '3.1.2 · Genetic tests', page: 63, color: '#9564df', icon: '🧬',
    objective: 'Explore how releasing and separating DNA prepares a sample for a molecular test.',
    principle: 'DNA must be separated from cellular material before many molecular analyses. A visible precipitate contains many molecules and may also contain impurities.',
    steps: [
      { title: 'Identify the sample', detail: 'Label a fictional cell sample and its matching preparation tube to preserve sample identity.', action: 'prepare' },
      { title: 'Release cell contents', detail: 'Add the prepared extraction solution and mix gently. Observe the model membranes breaking apart.', action: 'calibrate' },
      { title: 'Separate the DNA', detail: 'Layer the prepared cold alcohol above the extract and observe material gathering at the interface.', action: 'run' },
      { title: 'Assess the preparation', detail: 'Record the illustrative yield. Explain why a visible precipitate alone cannot identify a gene variant.', action: 'record' },
    ],
    equipment: ['Labelled cell sample', 'Extraction tube', 'Prepared extraction solution', 'Cold alcohol', 'Transfer pipette'],
    parameter: { label: 'Cold ethanol volume', unit: 'mL', min: 0.5, max: 8, step: 0.5, value: 2 },
    variable: 'Change cold ethanol volume and compare the model relative recovery of DNA.',
    controls: 'Keep starting sample volume, cell concentration and extraction conditions constant.',
    caution: 'Alcohol is flammable. This preparation uses fictional specimens.',
    simLimit: 'A supporting sample-preparation model, not a specified extraction protocol. Recovery values are illustrative, not laboratory yields.',
    question: { prompt: 'What does a visible DNA precipitate tell you?', options: ['It proves that a particular gene variant is present.', 'Material has been recovered, but further analysis is needed to identify a variant.', 'The sample contains no proteins.'], answer: 1, explanation: 'Precipitation is a preparation step. Sequence-specific or other validated molecular analysis is needed to test for a particular variant.' },
  },
  {
    id: 'aaq-gel', scene: 'gel', group: 'genetics', linkedUnits: ['F172'], title: 'DNA electrophoresis', subtitle: 'Read a model DNA profile',
    unit: 'F173', topic: '3.4 · Separation techniques', page: 76, color: '#8263dc', icon: '▥',
    objective: 'Separate model DNA fragments and compare their positions with a size ladder.',
    principle: 'Negatively charged DNA moves towards the positive electrode. In this gel model, shorter fragments move further than longer fragments.',
    steps: [
      { title: 'Prepare the chamber', detail: 'Position the wells near the negative electrode and cover the gel with the prepared buffer.', action: 'prepare' },
      { title: 'Load reference and sample', detail: 'Load a DNA size ladder and fictional samples into separate wells.', action: 'calibrate' },
      { title: 'Run the separation', detail: 'Choose a model fragment length and switch on the power. Watch the bands migrate through the gel.', action: 'run' },
      { title: 'Read the bands', detail: 'Compare positions within this gel. Record whether the unknown matches the supplied reference pattern.', action: 'record' },
    ],
    equipment: ['Gel tank', 'Agarose gel', 'Micropipette', 'DNA size ladder', 'Model DNA samples', 'Power supply'],
    parameter: { label: 'DNA fragment length', unit: 'bp', min: 100, max: 3000, step: 100, value: 1000 },
    variable: 'Change model fragment length and compare migration distance.',
    controls: 'Keep gel composition, voltage, run time and loading volume constant.',
    caution: 'A real electrophoresis chamber must be isolated from power before handling.',
    simLimit: 'Band patterns and timing are illustrative. This is linked to F172 molecular testing but is not a clinical genetic diagnosis.',
    question: { prompt: 'Which model fragment should travel furthest from its well?', options: ['The longest fragment.', 'Every fragment travels the same distance.', 'The shortest fragment.'], answer: 2, explanation: 'Shorter DNA fragments pass through the gel matrix more readily under the same conditions.' },
  },
  {
    id: 'aaq-colorimetry', scene: 'colorimeter', group: 'biomedical', linkedUnits: ['F174'], title: 'Protein colorimetry', subtitle: 'Build a calibration curve',
    unit: 'F173', topic: '3.5.2 · Colorimetry', page: 77, color: '#39a6a5', icon: '◈',
    objective: 'Measure model protein standards and build a concentration–absorbance calibration curve.',
    principle: 'A coloured protein assay absorbs light. Within its calibrated working range, absorbance increases approximately in proportion to concentration.',
    steps: [
      { title: 'Prepare the standards', detail: 'Arrange the supplied reagent-treated standards. Match cuvette fill levels and orientation.', action: 'prepare' },
      { title: 'Zero and calibrate', detail: 'Use the reagent blank to zero the instrument, then measure the standards at the fixed assay wavelength.', action: 'calibrate' },
      { title: 'Measure a standard', detail: 'Choose the prepared standard concentration, insert its cuvette and read absorbance.', action: 'run' },
      { title: 'Build the curve', detail: 'Repeat at several concentrations. Plot absorbance against concentration and explain how the curve could estimate an unknown.', action: 'record' },
    ],
    equipment: ['Colorimeter', 'Matched cuvettes', 'Protein standards', 'Reagent blank', 'Transfer pipette'],
    parameter: { label: 'Model sample concentration', unit: 'g dm⁻³', min: 0, max: 5, step: 0.5, value: 2 },
    variable: 'Change the model sample concentration and measure absorbance.',
    controls: 'Keep wavelength, path length, reagent treatment and reaction time constant.',
    caution: 'Avoid contact with assay reagents. Handle cuvettes by their non-optical faces.',
    simLimit: 'The calibration uses synthetic teaching data. Real assays have validated working ranges, measurement noise and sample-matrix effects.',
    question: { prompt: 'Why is a reagent blank used?', options: ['To remove absorbance due to the cuvette, solvent and reagents.', 'To make every sample have the same concentration.', 'To increase the concentration of the unknown.'], answer: 0, explanation: 'The blank accounts for background absorbance so the measured signal can be related to the analyte.' },
  },
  {
    id: 'aaq-centrifuge', scene: 'centrifuge', group: 'biomedical', linkedUnits: ['F173'], title: 'Cell fractionation', subtitle: 'Separate pellet and supernatant',
    unit: 'F170', topic: '1.1.2 · Observing cells and organelles', page: 35, color: '#599bbb', icon: '◎',
    objective: 'Model how a balanced centrifuge separates a cell homogenate into fractions.',
    principle: 'Particles sediment at different rates. Sequential spins can enrich different fractions, while the remaining liquid is the supernatant.',
    steps: [
      { title: 'Load matching tubes', detail: 'Place the model homogenate and an equal-mass balance tube opposite each other in the rotor.', action: 'prepare' },
      { title: 'Choose the spin', detail: 'Select rotor speed and calculate the force for the 8.0 cm rotor. Keep duration and sample preparation fixed.', action: 'calibrate' },
      { title: 'Separate the fraction', detail: 'Close the lid and run the rotor. Watch a pellet collect and the supernatant become clearer.', action: 'run' },
      { title: 'Compare force and speed', detail: 'Record relative centrifugal force. Explain why doubling speed quadruples force, and why a pellet may contain mixed material.', action: 'record' },
    ],
    equipment: ['Centrifuge', 'Homogenate tube', 'Balance tube', 'Collection tube', 'Transfer pipette'],
    parameter: { label: 'Rotor speed', unit: 'rpm', min: 1000, max: 6000, step: 500, value: 3000 },
    variable: 'Change rotor speed and calculate relative centrifugal force.',
    controls: 'Keep the 8.0 cm rotor radius, tube balance, duration, temperature and starting homogenate constant.',
    caution: 'Balance opposing tubes and wait for a complete stop before opening a real centrifuge.',
    simLimit: 'Fractions are illustrative and not validated centrifugation settings. Also supports F173 3.4, page 76.',
    question: { prompt: 'What is the liquid above the pellet called?', options: ['The precipitating electrode.', 'The supernatant.', 'The graticule.'], answer: 1, explanation: 'The pellet contains sedimented material; the supernatant is the liquid above it.' },
  },
  {
    id: 'aaq-respiration', scene: 'respirometer', group: 'physiology', linkedUnits: ['F170'], title: 'Respiration and metabolism', subtitle: 'Measure oxygen uptake',
    unit: 'F174', topic: '3.1.2 · Metabolic rates', page: 88, color: '#da9860', icon: '◌',
    objective: 'Use a model respirometer to calculate oxygen uptake per minute for a fixed sample mass.',
    principle: 'When carbon dioxide is absorbed, oxygen consumption reduces gas volume in a sealed respirometer. A matched control helps account for environmental changes.',
    steps: [
      { title: 'Prepare matched chambers', detail: 'Use the supplied model respiring sample and an inert control. Keep the carbon dioxide absorber separated from the sample.', action: 'prepare' },
      { title: 'Equilibrate and zero', detail: 'Set the model temperature and allow equilibration before setting both markers to zero.', action: 'calibrate' },
      { title: 'Measure gas change', detail: 'Start the timed run and observe the capillary marker move as oxygen is consumed.', action: 'run' },
      { title: 'Calculate uptake rate', detail: 'Subtract the control volume change, then divide by elapsed time. Account for mass if comparing different sample sizes.', action: 'record' },
    ],
    equipment: ['Model respirometer', 'Inert control chamber', 'Water bath', 'Capillary scale', 'Timer'],
    parameter: { label: 'Model temperature', unit: '°C', min: 10, max: 50, step: 5, value: 25 },
    variable: 'Change model temperature and compare oxygen uptake per minute.',
    controls: 'Keep sample mass, sample type, apparatus volume and measurement time constant.',
    caution: 'Real carbon dioxide absorbers require appropriate handling and separation from living samples.',
    simLimit: 'A supporting metabolism model, not a measurement of a person. Its temperature optimum and rates are illustrative.',
    question: { prompt: 'Why include a matched inert control?', options: ['To supply extra oxygen to the sample.', 'To make the sample respire faster.', 'To estimate gas-volume changes unrelated to respiration.'], answer: 2, explanation: 'Temperature or pressure changes can move a marker even without respiration. The control helps identify that contribution.' },
  },
  {
    id: 'aaq-lipase', scene: 'enzyme', group: 'physiology', linkedUnits: ['F173'], title: 'Lipase and digestion', subtitle: 'Follow an enzyme reaction',
    unit: 'F174', topic: '1.3.1 · Digestion', page: 86, color: '#dfaa45', icon: '⚗',
    objective: 'Investigate how temperature changes the time for a model lipase mixture to reach a pH endpoint.',
    principle: 'Lipase hydrolyses lipids, releasing fatty acids. The falling pH changes the indicator; a shorter endpoint time suggests a faster reaction under matched conditions.',
    steps: [
      { title: 'Prepare matched mixtures', detail: 'Use equal volumes of the prepared lipid emulsion and indicator. Include a control without active lipase.', action: 'prepare' },
      { title: 'Set the temperature', detail: 'Equilibrate both mixtures in the model water bath before starting the reaction.', action: 'calibrate' },
      { title: 'Add lipase and time', detail: 'Add the same amount of lipase and start the timer. Observe the colour change as acids form.', action: 'run' },
      { title: 'Compare rates', detail: 'Record endpoint time and compare 1/time across temperatures. Repeat before deciding on a trend.', action: 'record' },
    ],
    equipment: ['Water bath', 'Reaction tubes', 'Prepared lipid emulsion', 'Lipase', 'Indicator', 'Timer'],
    parameter: { label: 'Water-bath temperature', unit: '°C', min: 10, max: 70, step: 5, value: 35 },
    variable: 'Change temperature; measure time to the same indicator endpoint.',
    controls: 'Keep lipase concentration, lipid volume, starting pH, mixing and endpoint constant.',
    caution: 'Avoid enzyme contact and take care with hot water. Use the prepared teaching mixture.',
    simLimit: 'A supporting digestion investigation. The model optimum is illustrative; real enzyme preparations differ.',
    question: { prompt: 'Why may the reaction slow at a high temperature?', options: ['The enzyme can denature, changing its active site.', 'All substrate molecules disappear before mixing.', 'Fatty acids become enzymes.'], answer: 0, explanation: 'High temperature can disrupt the enzyme structure and reduce catalytic activity. The optimum depends on the enzyme and conditions.' },
  },
  {
    id: 'aaq-foodtests', scene: 'foodtest', group: 'physiology', linkedUnits: ['F174'], title: 'Biochemical food tests', subtitle: 'Identify reducing sugars',
    unit: 'F173', topic: '3.3.1 · Organic-compound tests', page: 75, color: '#cf855e', icon: '🧪',
    objective: 'Use a model Benedict’s test with a positive control and a reagent blank.',
    principle: 'A reducing sugar can produce a coloured copper(I) oxide precipitate on heating with Benedict’s reagent. Colour gives an approximate comparison, not a precise concentration.',
    steps: [
      { title: 'Label the tubes', detail: 'Arrange the unknown, a known reducing-sugar control and a water blank in the rack.', action: 'prepare' },
      { title: 'Add matched reagent', detail: 'Add equal reagent volumes to equal sample volumes and mix each tube consistently.', action: 'calibrate' },
      { title: 'Heat in the bath', detail: 'Run the model water bath for the same duration and observe any precipitate and colour change.', action: 'run' },
      { title: 'Interpret the result', detail: 'Compare with both controls and record the observation separately from your conclusion.', action: 'record' },
    ],
    equipment: ['Test-tube rack', 'Sample tubes', 'Benedict’s reagent', 'Positive control', 'Water blank', 'Water bath'],
    parameter: { label: 'Model reducing sugar', unit: '%', min: 0, max: 4, step: 1, value: 1 },
    variable: 'Change the reducing-sugar concentration and compare the model test colour.',
    controls: 'Keep sample and reagent volumes, bath temperature and heating time constant.',
    caution: 'Use eye protection with reagents and avoid contact with hot tubes.',
    simLimit: 'Colour bands are illustrative. This test does not distinguish glucose from every other reducing sugar. Also links to F174 1.1, page 85.',
    question: { prompt: 'A positive Benedict’s test supports which conclusion?', options: ['Only glucose can be present.', 'A reducing substance is present under the test conditions.', 'Protein concentration is exactly known.'], answer: 1, explanation: 'Benedict’s test is not specific to glucose. Controls and further tests are needed for stronger identification.' },
  },
  {
    id: 'aaq-spirometry', scene: 'spirometer', group: 'physiology', linkedUnits: ['F171'], title: 'Spirometry', subtitle: 'Lung volumes and ventilation',
    unit: 'F170', topic: '2.2.3 · Measuring body systems', page: 42, color: '#63a9c5', icon: '〰',
    objective: 'Read a model breathing trace and calculate pulmonary ventilation rate.',
    principle: 'Tidal volume is the volume moved in one ordinary breath. Multiplying it by breathing frequency gives minute ventilation.',
    steps: [
      { title: 'Prepare the instrument', detail: 'Connect the fictional participant to the model mouthpiece and check the volume scale.', action: 'prepare' },
      { title: 'Set a steady pattern', detail: 'Choose the fictional participant’s activity level and allow the model breathing pattern to stabilise.', action: 'calibrate' },
      { title: 'Record the trace', detail: 'Start the volume recording and observe inspiration and expiration on the moving trace.', action: 'run' },
      { title: 'Calculate ventilation', detail: 'Read tidal volume, count breaths per minute and multiply. Keep litres and cubic centimetres consistent.', action: 'record' },
    ],
    equipment: ['Model spirometer', 'Mouthpiece', 'Breathing tube', 'Volume trace', 'Timer'],
    parameter: { label: 'Model exercise intensity', unit: '%', min: 0, max: 100, step: 25, value: 0 },
    variable: 'Change model activity; measure breathing frequency, tidal volume and minute ventilation.',
    controls: 'Use the same model participant, apparatus, measurement duration and steady-state timing.',
    caution: 'Real respiratory measurements need suitable hygiene procedures and trained supervision.',
    simLimit: 'A synthetic breathing trace, not a lung-function assessment. Simple spirometry cannot directly measure residual volume.',
    question: { prompt: 'At 12 breaths/min and 0.5 L per breath, what is minute ventilation?', options: ['0.042 L/min', '24 L/min', '6 L/min'], answer: 2, explanation: '12 breaths/min × 0.5 L/breath = 6 L/min.' },
  },
  {
    id: 'aaq-cardiovascular', scene: 'pulse', group: 'physiology', linkedUnits: ['F171'], title: 'Cardiovascular response', subtitle: 'Pulse and cardiac output',
    unit: 'F170', topic: '2.2.3 · Measuring body systems', page: 42, color: '#dc718a', icon: '♥',
    objective: 'Read a synthetic pulse trace and calculate cardiac output from heart rate and model stroke volume.',
    principle: 'Heart rate counts beats per minute. Multiplying it by stroke volume gives cardiac output. Blood pressure is a separate measurement, not a value derived from heart rate alone.',
    steps: [
      { title: 'Prepare the monitor', detail: 'Position the model monitor and pulse sensor. Identify the cuff as an example of additional circulation monitoring.', action: 'prepare' },
      { title: 'Establish a baseline', detail: 'Choose the model activity level and observe a steady pulse before taking a measurement.', action: 'calibrate' },
      { title: 'Run a measurement', detail: 'Start the synthetic recording and observe the spacing of the pulse peaks.', action: 'run' },
      { title: 'Calculate cardiac output', detail: 'Multiply heart rate by the supplied stroke volume. Convert cubic centimetres to cubic decimetres.', action: 'record' },
    ],
    equipment: ['Model upper-arm cuff', 'Pressure monitor', 'Pulse sensor', 'Timer'],
    parameter: { label: 'Model exercise intensity', unit: '%', min: 0, max: 100, step: 25, value: 0 },
    variable: 'Change model activity and compare heart rate, stroke volume and cardiac output.',
    controls: 'Use the same model participant, sensor position, measurement duration and steady-state timing.',
    caution: 'The displayed values belong to a fictional participant and are for interpretation practice.',
    simLimit: 'Changing heart rate alone does not determine blood pressure. Also supports F171 4.1, page 55; this is not a medical assessment.',
    question: { prompt: 'At 70 beats/min and 70 cm³ per beat, what is cardiac output?', options: ['4.9 dm³/min', '1 dm³/min', '4900 dm³/min'], answer: 0, explanation: '70 × 70 = 4900 cm³/min. Dividing by 1000 gives 4.9 dm³/min.' },
  },
  {
    id: 'aaq-response', scene: 'reflex', group: 'physiology', linkedUnits: ['F170'], title: 'Visual response time', subtitle: 'Measure a conscious response',
    unit: 'F176', topic: '2.2.1 · Control of movement', page: 109, color: '#b981d1', icon: 'ϟ',
    objective: 'Convert a model ruler-drop distance into a visual–motor response time.',
    principle: 'A freely falling ruler accelerates under gravity. Its drop distance can estimate the delay before a catch: time = √(2 × distance / g).',
    steps: [
      { title: 'Align the ruler', detail: 'Place the zero mark level with the model fingertips and keep the same starting position.', action: 'prepare' },
      { title: 'Set the catch distance', detail: 'Choose a synthetic catch distance to explore the response delay that it represents.', action: 'calibrate' },
      { title: 'Drop and catch', detail: 'Release the ruler in the animation and observe the distance it falls before the model hand catches it.', action: 'run' },
      { title: 'Convert and compare', detail: 'Convert centimetres to metres before calculating time. Consider anticipation and repeated practice as sources of bias.', action: 'record' },
    ],
    equipment: ['Model ruler', 'Catch marker', 'Timer', 'Results table'],
    parameter: { label: 'Model catch distance', unit: 'cm', min: 5, max: 50, step: 1, value: 20 },
    variable: 'Change the synthetic catch distance and calculate response time.',
    controls: 'Keep gravitational acceleration, starting position and release conditions constant.',
    caution: 'Only the animated participant performs this test; no personal health data are collected.',
    simLimit: 'This is a conscious visual–motor response, not a spinal reflex. The synthetic catch distance does not measure your response speed.',
    question: { prompt: 'Why should this activity not be called a spinal reflex test?', options: ['Gravity stops acting when a person sees the ruler.', 'Seeing and catching the ruler involves conscious visual–motor processing.', 'A ruler has no measurable acceleration.'], answer: 1, explanation: 'The task involves visual perception and a coordinated voluntary catch; it does not isolate a spinal reflex arc.' },
  },
  {
    id: 'aaq-antimicrobial', scene: 'antimicrobial', group: 'biomedical', linkedUnits: ['F173', 'F170'], title: 'Antimicrobial screening', subtitle: 'Compare inhibition zones',
    unit: 'F177', topic: '2.2 · Drug discovery', page: 125, color: '#6bb88e', icon: '◉',
    objective: 'Compare model inhibition zones around a candidate antimicrobial disc and a solvent control.',
    principle: 'A compound diffuses into agar. A clear zone can occur where growth is inhibited; its size also depends on diffusion and assay conditions.',
    steps: [
      { title: 'Inspect the model plate', detail: 'Use the supplied virtual lawn plate and identify the candidate and solvent-control discs.', action: 'prepare' },
      { title: 'Set the candidate level', detail: 'Choose a fictional disc dose while holding disc size and the virtual culture conditions constant.', action: 'calibrate' },
      { title: 'Reveal the result', detail: 'Run the accelerated animation and observe the clear zone around the candidate disc.', action: 'run' },
      { title: 'Measure and evaluate', detail: 'Measure the whole clear-zone diameter through the disc centre. Compare repeats and explain the limitations of this screen.', action: 'record' },
    ],
    equipment: ['Virtual lawn plate', 'Candidate disc', 'Solvent-control disc', 'Forceps', 'Millimetre scale'],
    parameter: { label: 'Fictional disc dose', unit: 'µg', min: 0, max: 30, step: 5, value: 10 },
    variable: 'Change the fictional disc dose and compare clear-zone diameter.',
    controls: 'Keep model organism, agar, disc dimensions, solvent and elapsed culture time constant.',
    caution: 'This activity uses virtual microorganisms only. Real culture work requires approved facilities, organisms and supervision.',
    simLimit: 'A conceptual discovery screen with no real culture protocol. Zone size alone does not establish clinical efficacy or prescribing suitability. Links to F173 2.4, page 73.',
    question: { prompt: 'Does the largest inhibition zone prove a candidate is the best clinical drug?', options: ['Yes, zone diameter alone establishes clinical effectiveness.', 'Yes, diffusion never affects zone size.', 'No; diffusion, toxicity, delivery and further testing also matter.'], answer: 2, explanation: 'A plate screen is only one kind of evidence. A candidate needs further investigation, including safety and behaviour in the body.' },
  },
];
