import {chromium} from 'playwright';
import fs from 'node:fs';

const out='/private/tmp/chem-hydrogen-ignition-raised';
fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});
const errors=[];
page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`)});
page.on('pageerror',error=>errors.push(`page: ${error.message}`));
await page.goto(`http://localhost:4173/?qa=${Date.now()}`,{waitUntil:'networkidle'});
await page.waitForTimeout(300);
await page.evaluate(()=>{window.__manualSimulationTime=true});
const state=async()=>JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
await page.mouse.click(135,385);
await page.mouse.click(382,657);
await page.evaluate(()=>window.advanceTime(2250));
await page.evaluate(()=>window.advanceTime(3500));
const ready=await state();
await page.mouse.click(382,657);
await page.evaluate(()=>window.advanceTime(240));
await page.waitForTimeout(120);
await page.screenshot({path:`${out}/raised-splint-approach.png`,fullPage:true});
const ignition=await state();
const result={ready:ready.hydrogen_practical,ignition:ignition.hydrogen_practical,renderer:ignition.renderer,errors};
fs.writeFileSync(`${out}/result.json`,JSON.stringify(result,null,2));
if(ready.hydrogen_practical?.stage!==3)throw new Error('Hydrogen did not reach sealed stage');
if(ignition.hydrogen_practical?.stage!==4||ignition.hydrogen_practical?.thumb_pose!=='withdrawing for splint')throw new Error('Raised splint stage or thumb pose is incorrect');
if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
console.log(JSON.stringify(result,null,2));
