import { chromium } from 'playwright';
import fs from 'node:fs';

const out = 'output/osmosis-visual-final';
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1 });
const errors = [];
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', error => errors.push(error.message));
await page.goto(`http://127.0.0.1:4173/?osmosis-visual=${Date.now()}`, { waitUntil: 'networkidle' });
await page.waitForFunction(() => typeof window.render_game_to_text === 'function');
await page.evaluate(() => { window.__manualSimulationTime = true; });
const advance = ms => page.evaluate(value => window.advanceTime(value), ms);
const capture = async name => { await page.waitForTimeout(120); await page.screenshot({ path: `${out}/${name}.png`, fullPage: true }); };
await page.mouse.click(320, 32);
await page.mouse.click(135, 236);
await capture('01-forceps-ready');
await page.mouse.click(387, 657);
await advance(900);
await capture('02-forceps-grip-transfer');
await advance(1900);
await advance(2700);
await capture('03-water-molecules-and-arrows');
await advance(3000);
await page.mouse.click(387, 657);
await advance(2920);
await capture('04-two-sheet-blotting-press');
const snapshot = JSON.parse(await page.evaluate(() => window.render_game_to_text()));
fs.writeFileSync(`${out}/summary.json`, JSON.stringify({ errors, stage: snapshot.potato_osmosis_practical.stage, animation: snapshot.potato_osmosis_practical.animation }, null, 2));
if (errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({ errors, stage: snapshot.potato_osmosis_practical.stage }, null, 2));
await browser.close();
