import { chromium } from 'playwright';
import fs from 'node:fs';

const out = 'output/potometer-visual-final';
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.POTOMETER_QA_CHROMIUM || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1 });
const errors = [];
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', error => errors.push(error.message));
await page.goto(`http://127.0.0.1:4173/?potometer-visual=${Date.now()}`, { waitUntil: 'networkidle' });
await page.waitForFunction(() => typeof window.render_game_to_text === 'function');
await page.evaluate(() => { window.__manualSimulationTime = true; });
const advance = ms => page.evaluate(value => window.advanceTime(value), ms);
const primary = () => page.mouse.click(382, 657);
const capture = async name => { await page.waitForTimeout(140); await page.screenshot({ path: `${out}/${name}.png`, fullPage: true }); };
await page.mouse.click(320, 32);
await page.mouse.click(135, 288);
await capture('01-angled-fan-and-graduated-rig');
await primary();
await advance(2700);
await capture('02-visible-single-bubble');
await primary();
await advance(2800);
await capture('03-bubble-aligned-zero');
await primary();
await advance(6400);
await primary();
await advance(2800);
await primary();
await advance(2800);
await capture('04-fan-airflow-leaf-flutter');
const snapshot = JSON.parse(await page.evaluate(() => window.render_game_to_text()));
fs.writeFileSync(`${out}/summary.json`, JSON.stringify({ errors, stage: snapshot.bubble_potometer_practical.stage, wind_speed_m_s: snapshot.bubble_potometer_practical.current_wind_speed_m_s, animation: snapshot.bubble_potometer_practical.animation }, null, 2));
if (errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({ errors, stage: snapshot.bubble_potometer_practical.stage, wind_speed_m_s: snapshot.bubble_potometer_practical.current_wind_speed_m_s }, null, 2));
await browser.close();
